# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ppcat < Formula
  desc "ppcat is a tool to format JSON in the middle of text."
  homepage "https://github.com/winebarrel/ppcat"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ppcat/releases/download/v0.1.0/ppcat_0.1.0_darwin_amd64.tar.gz"
      sha256 "a810d392f849d4fde380ccacf4542d5c387df70d116a6c7af7dc8fdc0cf60f78"

      def install
        bin.install 'ppcat'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/ppcat/releases/download/v0.1.0/ppcat_0.1.0_darwin_arm64.tar.gz"
      sha256 "b4fbc9de7d07cf9e60206e6f8c6eee4d4b8c0d454c05fe350711487757f0ccb4"

      def install
        bin.install 'ppcat'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/ppcat/releases/download/v0.1.0/ppcat_0.1.0_linux_arm64.tar.gz"
      sha256 "2d87ab6c503f06cb6dbaa31f9f59a2a761ee7068506754ae972fc5ef21b7c5e5"

      def install
        bin.install 'ppcat'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ppcat/releases/download/v0.1.0/ppcat_0.1.0_linux_amd64.tar.gz"
      sha256 "f53477f14e1794c3255b405f48cf2e3a1bfe2e3b61fc84f34cd4a064ca0df7c0"

      def install
        bin.install 'ppcat'
      end
    end
  end
end
