# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ppcat < Formula
  desc "ppcat is a tool to format JSON in the middle of text."
  homepage "https://github.com/winebarrel/ppcat"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ppcat/releases/download/v0.2.1/ppcat_0.2.1_darwin_amd64.tar.gz"
      sha256 "0ac115fc87a41bc207f40fc79421063fe4c12a07ee0e4b67d881f327e636f12c"

      def install
        bin.install 'ppcat'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/ppcat/releases/download/v0.2.1/ppcat_0.2.1_darwin_arm64.tar.gz"
      sha256 "b8bcc3ceedd59c833abaddc75ce8da25d7461dff7e407c75a99c4fbf1ec13564"

      def install
        bin.install 'ppcat'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/ppcat/releases/download/v0.2.1/ppcat_0.2.1_linux_arm64.tar.gz"
      sha256 "6ec35a326f2a2b26bbfe7dd48fe9b3b54dd4bc12b348b32e2941cc69926135f5"

      def install
        bin.install 'ppcat'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ppcat/releases/download/v0.2.1/ppcat_0.2.1_linux_amd64.tar.gz"
      sha256 "5dee8dca1ca1dc18a1ec67bbc9d92ea5fd3eccdc584764bd14130c739cd68fc6"

      def install
        bin.install 'ppcat'
      end
    end
  end
end
